Build from source in scheduled tests (#172)
* build from source & force reinstall
* run scheduled tests in parallel
* general output cleanups/fixes/improvements
* improve dependencies of stages

diff --git a/.azure-ci/steps/test-formulae-from-source.yml b/.azure-ci/steps/test-formulae-from-source.yml
--- a/.azure-ci/steps/test-formulae-from-source.yml
+++ b/.azure-ci/steps/test-formulae-from-source.yml
@@ -1,34 +1,26 @@
-# File: /.azure-ci/steps/test-formulae.yml
+# File: /.azure-ci/steps/test-formulae-from-source.yml
 
 steps:
 
   - bash: |
       FAILING_FORMULAE=""
 
-      for formula in Formula/* ; do
+      FORMULAE_TO_TEST=(avr-binutils avr-gcc avr-gdb)
 
-        formula=$(basename $formula ".rb")
+      for formula in "${FORMULAE_TO_TEST[@]}" ; do
 
         echo ""
         echo "🏗️ Installing $formula"
 
-        if brew install $formula 2>/dev/null ; then
+        brew reinstall --build-from-source $formula && brew test $formula && brew linkage --test $formula
 
-          brew install --build-from-source $formula && brew linkage --test $formula
-
-          if [ $? -eq 1 ]; then
-            echo ""
-            echo "💥 $formula test failed"
-            FAILING_FORMULAE+=" $formula"
-          else
-            echo ""
-            echo "✅ $formula test succeeded"
-          fi
-
+        if [ $? -eq 1 ]; then
+          echo ""
+          echo "💥 $formula test failed"
+          FAILING_FORMULAE+=" $formula"
         else
-
-          echo "$formula is --HEAD only, skipping tests."
-
+          echo ""
+          echo "✅ $formula test succeeded"
         fi
 
       done
@@ -49,12 +41,11 @@ steps:
         done
 
         echo ""
-        echo "🚧 A new PR will be created to bump the revision and rebuild the formulae. 🏗"
-
-        echo "##vso[task.setvariable variable=failing_formulae;isOutput=true]$FAILING_FORMULAE"
+        echo "🚧 Check the issues and create PRs 🏗"
+        exit 1
 
       fi
-    displayName: Step - Test Formulae
+    displayName: Test Formulae
     name: test_formulae
 
 
