fix test from source

diff --git a/.azure-ci/steps/test-formulae-from-source.yml b/.azure-ci/steps/test-formulae-from-source.yml
--- a/.azure-ci/steps/test-formulae-from-source.yml
+++ b/.azure-ci/steps/test-formulae-from-source.yml
@@ -12,23 +12,15 @@ steps:
         echo ""
         echo "🏗️ Installing $formula"
 
-        if brew install $formula 2>/dev/null ; then
+        brew install --build-from-source $formula && brew test $formula && brew linkage --test $formula
 
-          brew install --build-from-source $formula && brew linkage --test $formula
-
-          if [ $? -eq 1 ]; then
-            echo ""
-            echo "💥 $formula test failed"
-            FAILING_FORMULAE+=" $formula"
-          else
-            echo ""
-            echo "✅ $formula test succeeded"
-          fi
-
+        if [ $? -eq 1 ]; then
+          echo ""
+          echo "💥 $formula test failed"
+          FAILING_FORMULAE+=" $formula"
         else
-
-          echo "$formula is --HEAD only, skipping tests."
-
+          echo ""
+          echo "✅ $formula test succeeded"
         fi
 
       done
