azure ci - improve schedule test output

diff --git a/.azure-ci/stages/stage-scheduled-test.yml b/.azure-ci/stages/stage-scheduled-test.yml
--- a/.azure-ci/stages/stage-scheduled-test.yml
+++ b/.azure-ci/stages/stage-scheduled-test.yml
@@ -31,15 +31,22 @@ stages:
 
               for formula in Formula/* ; do
 
-                echo "\n"
+                echo -e "\n"
                 echo "Installing $formula"
-                brew install $formula
 
-                echo "\n"
-                brew test $formula && brew linkage --test $formula
+                if brew install $formula 2>/dev/null ; then
 
-                if [ $? -eq 1 ]; then
-                  FAILING_FORMULAE+=$formula
+                  echo -e "\n"
+                  brew test $formula && brew linkage --test $formula
+
+                  if [ $? -eq 1 ]; then
+                    FAILING_FORMULAE+=$formula
+                  fi
+
+                else
+
+                  echo "$formula is --HEAD only, skipping tests."
+
                 fi
 
               done
@@ -51,10 +58,15 @@ stages:
 
               else
 
-                echo "💥 The following formulae failed: ⚠️"
-                echo "\t$FAILING_FORMULAE"
-                echo "🚧 A new PR will be created to bump the revision and rebuild"
-                echo "the formulae.🏗"
+                echo "💥 The following formulae failed:"
+
+                for f in $FAILING_FORMULAE; do
+                  echo -e "  - $f"
+                done
+
+                echo -e "\n"
+
+                echo "🚧 A new PR will be created to bump the revision and rebuild the formulae. 🏗"
 
                 echo "##vso[task.setvariable variable=failing_formulae;isOutput=true]$FAILING_FORMULAE"
 
